MAINTAINER belHak GitHub: https://github.com/belHak
FROM toothpasteeater/default-java-11:latest
ADD target/userI-application.jar userI-application.jar
EXPOSE 8082
ENTRYPOINT ["java","-jar","userI-application.jar"]